id: PB93F2AE3
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: en
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    cd95c512c4ab45e4adb9d5efdecfbc64:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    80d458a4d2974cea922be81dba6d7e13:
      title: An Aspiration
      parent: Aspiration Prayers
    9f282c48aee045bf88def1ffda69a6eb:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    7e4c86996f3d4e878e2abc1f1c0bffbf:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    ba8578ee725141d78d81a3f59f6a4724:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    bb89de56ee894de8b30a722b38e3cb66:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    4014a5b805614529873612bb6a8702c1:
      title: A Prayer
      parent: Prayers
    e66080be7fae4eae81167dc836691d03:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    6492f412a6de4786913f032e3f116ec3:
      title: A Prayer to Padmasambhava
      parent: Prayers
    679b76750ff244d59448c5d6b3b2b5e7:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    0ff52e638a484812a10362e28f1426b2:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    1bb86e46cf044a968a56eab40011b533:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    1096242bf8064658be1b73c5c661a001:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.942671'
last_modified_at: '2022-02-28T23:06:52.942677'
